// <auto-generated />
namespace TeduShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addreferencetouser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addreferencetouser));
        
        string IMigrationMetadata.Id
        {
            get { return "201706100812533_add-reference-touser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
